export const data = [
  {
    userId: 1,
    id: 1,
    title:
      "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
  },
  {
    userId: 1,
    id: 2,
    title: "qui est esse",
    body: "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
  },
  {
    userId: 1,
    id: 3,
    title: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    body: "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
  },
  {
    userId: 1,
    id: 4,
    title: "eum et est occaecati",
    body: "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
  },
  {
    userId: 1,
    id: 5,
    title: "nesciunt quas odio",
    body: "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
  },
  {
    userId: 1,
    id: 6,
    title: "dolorem eum magni eos aperiam quia",
    body: "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
  },
  {
    userId: 1,
    id: 7,
    title: "magnam facilis autem",
    body: "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
  },
  {
    userId: 1,
    id: 8,
    title: "dolorem dolore est ipsam",
    body: "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
  },
  {
    userId: 1,
    id: 9,
    title: "nesciunt iure omnis dolorem tempora et accusantium",
    body: "consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas",
  },
  {
    userId: 1,
    id: 10,
    title: "optio molestias id quia eum",
    body: "quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error",
  },
  {
    userId: 2,
    id: 11,
    title: "et ea vero quia laudantium autem",
    body: "delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi",
  },
  {
    userId: 2,
    id: 12,
    title: "in quibusdam tempore odit est dolorem",
    body: "itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio",
  },
  {
    userId: 2,
    id: 13,
    title: "dolorum ut in voluptas mollitia et saepe quo animi",
    body: "aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam",
  },
  {
    userId: 2,
    id: 14,
    title: "voluptatem eligendi optio",
    body: "fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum",
  },
  {
    userId: 2,
    id: 15,
    title: "eveniet quod temporibus",
    body: "reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae",
  },
  {
    userId: 2,
    id: 16,
    title:
      "sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio",
    body: "suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta",
  },
  {
    userId: 2,
    id: 17,
    title: "fugit voluptas sed molestias voluptatem provident",
    body: "eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo",
  },
  {
    userId: 2,
    id: 18,
    title: "voluptate et itaque vero tempora molestiae",
    body: "eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluptatem vel debitis et magnam",
  },
  {
    userId: 2,
    id: 19,
    title: "adipisci placeat illum aut reiciendis qui",
    body: "illum quis cupiditate provident sit magnam\nea sed aut omnis\nveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas",
  },
  {
    userId: 2,
    id: 20,
    title: "doloribus ad provident suscipit at",
    body: "qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo",
  },
  {
    userId: 3,
    id: 21,
    title: "asperiores ea ipsam voluptatibus modi minima quia sint",
    body: "repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nnihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt",
  },
  {
    userId: 3,
    id: 22,
    title: "dolor sint quo a velit explicabo quia nam",
    body: "eos qui et ipsum ipsam suscipit aut\nsed omnis non odio\nexpedita earum mollitia molestiae aut atque rem suscipit\nnam impedit esse",
  },
  {
    userId: 3,
    id: 23,
    title: "maxime id vitae nihil numquam",
    body: "veritatis unde neque eligendi\nquae quod architecto quo neque vitae\nest illo sit tempora doloremque fugit quod\net et vel beatae sequi ullam sed tenetur perspiciatis",
  },
  {
    userId: 3,
    id: 24,
    title: "autem hic labore sunt dolores incidunt",
    body: "enim et ex nulla\nomnis voluptas quia qui\nvoluptatem consequatur numquam aliquam sunt\ntotam recusandae id dignissimos aut sed asperiores deserunt",
  },
  {
    userId: 3,
    id: 25,
    title: "rem alias distinctio quo quis",
    body: "ullam consequatur ut\nomnis quis sit vel consequuntur\nipsa eligendi ipsum molestiae et omnis error nostrum\nmolestiae illo tempore quia et distinctio",
  },
  {
    userId: 3,
    id: 26,
    title: "est et quae odit qui non",
    body: "similique esse doloribus nihil accusamus\nomnis dolorem fuga consequuntur reprehenderit fugit recusandae temporibus\nperspiciatis cum ut laudantium\nomnis aut molestiae vel vero",
  },
  {
    userId: 3,
    id: 27,
    title: "quasi id et eos tenetur aut quo autem",
    body: "eum sed dolores ipsam sint possimus debitis occaecati\ndebitis qui qui et\nut placeat enim earum aut odit facilis\nconsequatur suscipit necessitatibus rerum sed inventore temporibus consequatur",
  },
  {
    userId: 3,
    id: 28,
    title: "delectus ullam et corporis nulla voluptas sequi",
    body: "non et quaerat ex quae ad maiores\nmaiores recusandae totam aut blanditiis mollitia quas illo\nut voluptatibus voluptatem\nsimilique nostrum eum",
  },
  {
    userId: 3,
    id: 29,
    title: "iusto eius quod necessitatibus culpa ea",
    body: "odit magnam ut saepe sed non qui\ntempora atque nihil\naccusamus illum doloribus illo dolor\neligendi repudiandae odit magni similique sed cum maiores",
  },
  {
    userId: 3,
    id: 30,
    title: "a quo magni similique perferendis",
    body: "alias dolor cumque\nimpedit blanditiis non eveniet odio maxime\nblanditiis amet eius quis tempora quia autem rem\na provident perspiciatis quia",
  },
  {
    userId: 4,
    id: 31,
    title: "ullam ut quidem id aut vel consequuntur",
    body: "debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae",
  },
  {
    userId: 4,
    id: 32,
    title: "doloremque illum aliquid sunt",
    body: "deserunt eos nobis asperiores et hic\nest debitis repellat molestiae optio\nnihil ratione ut eos beatae quibusdam distinctio maiores\nearum voluptates et aut adipisci ea maiores voluptas maxime",
  },
  {
    userId: 4,
    id: 33,
    title: "qui explicabo molestiae dolorem",
    body: "rerum ut et numquam laborum odit est sit\nid qui sint in\nquasi tenetur tempore aperiam et quaerat qui in\nrerum officiis sequi cumque quod",
  },
  {
    userId: 4,
    id: 34,
    title: "magnam ut rerum iure",
    body: "ea velit perferendis earum ut voluptatem voluptate itaque iusto\ntotam pariatur in\nnemo voluptatem voluptatem autem magni tempora minima in\nest distinctio qui assumenda accusamus dignissimos officia nesciunt nobis",
  },
  {
    userId: 4,
    id: 35,
    title: "id nihil consequatur molestias animi provident",
    body: "nisi error delectus possimus ut eligendi vitae\nplaceat eos harum cupiditate facilis reprehenderit voluptatem beatae\nmodi ducimus quo illum voluptas eligendi\net nobis quia fugit",
  },
  {
    userId: 4,
    id: 36,
    title: "fuga nam accusamus voluptas reiciendis itaque",
    body: "ad mollitia et omnis minus architecto odit\nvoluptas doloremque maxime aut non ipsa qui alias veniam\nblanditiis culpa aut quia nihil cumque facere et occaecati\nqui aspernatur quia eaque ut aperiam inventore",
  },
  {
    userId: 4,
    id: 37,
    title: "provident vel ut sit ratione est",
    body: "debitis et eaque non officia sed nesciunt pariatur vel\nvoluptatem iste vero et ea\nnumquam aut expedita ipsum nulla in\nvoluptates omnis consequatur aut enim officiis in quam qui",
  },
  {
    userId: 4,
    id: 38,
    title: "explicabo et eos deleniti nostrum ab id repellendus",
    body: "animi esse sit aut sit nesciunt assumenda eum voluptas\nquia voluptatibus provident quia necessitatibus ea\nrerum repudiandae quia voluptatem delectus fugit aut id quia\nratione optio eos iusto veniam iure",
  },
  {
    userId: 4,
    id: 39,
    title: "eos dolorem iste accusantium est eaque quam",
    body: "corporis rerum ducimus vel eum accusantium\nmaxime aspernatur a porro possimus iste omnis\nest in deleniti asperiores fuga aut\nvoluptas sapiente vel dolore minus voluptatem incidunt ex",
  },
  {
    userId: 4,
    id: 40,
    title: "enim quo cumque",
    body: "ut voluptatum aliquid illo tenetur nemo sequi quo facilis\nipsum rem optio mollitia quas\nvoluptatem eum voluptas qui\nunde omnis voluptatem iure quasi maxime voluptas nam",
  },
  {
    userId: 5,
    id: 41,
    title: "non est facere",
    body: "molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe",
  },
  {
    userId: 5,
    id: 42,
    title:
      "commodi ullam sint et excepturi error explicabo praesentium voluptas",
    body: "odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut",
  },
  {
    userId: 5,
    id: 43,
    title:
      "eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis",
    body: "similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis",
  },
  {
    userId: 5,
    id: 44,
    title: "optio dolor molestias sit",
    body: "temporibus est consectetur dolore\net libero debitis vel velit laboriosam quia\nipsum quibusdam qui itaque fuga rem aut\nea et iure quam sed maxime ut distinctio quae",
  },
  {
    userId: 5,
    id: 45,
    title: "ut numquam possimus omnis eius suscipit laudantium iure",
    body: "est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem",
  },
  {
    userId: 5,
    id: 46,
    title: "aut quo modi neque nostrum ducimus",
    body: "voluptatem quisquam iste\nvoluptatibus natus officiis facilis dolorem\nquis quas ipsam\nvel et voluptatum in aliquid",
  },
  {
    userId: 5,
    id: 47,
    title: "quibusdam cumque rem aut deserunt",
    body: "voluptatem assumenda ut qui ut cupiditate aut impedit veniam\noccaecati nemo illum voluptatem laudantium\nmolestiae beatae rerum ea iure soluta nostrum\neligendi et voluptate",
  },
  {
    userId: 5,
    id: 48,
    title: "ut voluptatem illum ea doloribus itaque eos",
    body: "voluptates quo voluptatem facilis iure occaecati\nvel assumenda rerum officia et\nillum perspiciatis ab deleniti\nlaudantium repellat ad ut et autem reprehenderit",
  },
  {
    userId: 5,
    id: 49,
    title: "laborum non sunt aut ut assumenda perspiciatis voluptas",
    body: "inventore ab sint\nnatus fugit id nulla sequi architecto nihil quaerat\neos tenetur in in eum veritatis non\nquibusdam officiis aspernatur cumque aut commodi aut",
  },
  {
    userId: 5,
    id: 50,
    title:
      "repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem",
    body: "error suscipit maxime adipisci consequuntur recusandae\nvoluptas eligendi et est et voluptates\nquia distinctio ab amet quaerat molestiae et vitae\nadipisci impedit sequi nesciunt quis consectetur",
  },
  {
    userId: 6,
    id: 51,
    title: "soluta aliquam aperiam consequatur illo quis voluptas",
    body: "sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem",
  },
  {
    userId: 6,
    id: 52,
    title: "qui enim et consequuntur quia animi quis voluptate quibusdam",
    body: "iusto est quibusdam fuga quas quaerat molestias\na enim ut sit accusamus enim\ntemporibus iusto accusantium provident architecto\nsoluta esse reprehenderit qui laborum",
  },
  {
    userId: 6,
    id: 53,
    title: "ut quo aut ducimus alias",
    body: "minima harum praesentium eum rerum illo dolore\nquasi exercitationem rerum nam\nporro quis neque quo\nconsequatur minus dolor quidem veritatis sunt non explicabo similique",
  },
  {
    userId: 6,
    id: 54,
    title: "sit asperiores ipsam eveniet odio non quia",
    body: "totam corporis dignissimos\nvitae dolorem ut occaecati accusamus\nex velit deserunt\net exercitationem vero incidunt corrupti mollitia",
  },
  {
    userId: 6,
    id: 55,
    title: "sit vel voluptatem et non libero",
    body: "debitis excepturi ea perferendis harum libero optio\neos accusamus cum fuga ut sapiente repudiandae\net ut incidunt omnis molestiae\nnihil ut eum odit",
  },
  {
    userId: 6,
    id: 56,
    title: "qui et at rerum necessitatibus",
    body: "aut est omnis dolores\nneque rerum quod ea rerum velit pariatur beatae excepturi\net provident voluptas corrupti\ncorporis harum reprehenderit dolores eligendi",
  },
  {
    userId: 6,
    id: 57,
    title: "sed ab est est",
    body: "at pariatur consequuntur earum quidem\nquo est laudantium soluta voluptatem\nqui ullam et est\net cum voluptas voluptatum repellat est",
  },
  {
    userId: 6,
    id: 58,
    title: "voluptatum itaque dolores nisi et quasi",
    body: "veniam voluptatum quae adipisci id\net id quia eos ad et dolorem\naliquam quo nisi sunt eos impedit error\nad similique veniam",
  },
  {
    userId: 6,
    id: 59,
    title: "qui commodi dolor at maiores et quis id accusantium",
    body: "perspiciatis et quam ea autem temporibus non voluptatibus qui\nbeatae a earum officia nesciunt dolores suscipit voluptas et\nanimi doloribus cum rerum quas et magni\net hic ut ut commodi expedita sunt",
  },
  {
    userId: 6,
    id: 60,
    title:
      "consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere",
    body: "asperiores sunt ab assumenda cumque modi velit\nqui esse omnis\nvoluptate et fuga perferendis voluptas\nillo ratione amet aut et omnis",
  },
  {
    userId: 7,
    id: 61,
    title: "voluptatem doloribus consectetur est ut ducimus",
    body: "ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit",
  },
  {
    userId: 7,
    id: 62,
    title: "beatae enim quia vel",
    body: "enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio",
  },
  {
    userId: 7,
    id: 63,
    title:
      "voluptas blanditiis repellendus animi ducimus error sapiente et suscipit",
    body: "enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta",
  },
  {
    userId: 7,
    id: 64,
    title: "et fugit quas eum in in aperiam quod",
    body: "id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est eos perspiciatis\nincidunt a error provident eaque aut aut qui",
  },
  {
    userId: 7,
    id: 65,
    title: "consequatur id enim sunt et et",
    body: "voluptatibus ex esse\nsint explicabo est aliquid cumque adipisci fuga repellat labore\nmolestiae corrupti ex saepe at asperiores et perferendis\nnatus id esse incidunt pariatur",
  },
  {
    userId: 7,
    id: 66,
    title: "repudiandae ea animi iusto",
    body: "officia veritatis tenetur vero qui itaque\nsint non ratione\nsed et ut asperiores iusto eos molestiae nostrum\nveritatis quibusdam et nemo iusto saepe",
  },
  {
    userId: 7,
    id: 67,
    title: "aliquid eos sed fuga est maxime repellendus",
    body: "reprehenderit id nostrum\nvoluptas doloremque pariatur sint et accusantium quia quod aspernatur\net fugiat amet\nnon sapiente et consequatur necessitatibus molestiae",
  },
  {
    userId: 7,
    id: 68,
    title: "odio quis facere architecto reiciendis optio",
    body: "magnam molestiae perferendis quisquam\nqui cum reiciendis\nquaerat animi amet hic inventore\nea quia deleniti quidem saepe porro velit",
  },
  {
    userId: 7,
    id: 69,
    title: "fugiat quod pariatur odit minima",
    body: "officiis error culpa consequatur modi asperiores et\ndolorum assumenda voluptas et vel qui aut vel rerum\nvoluptatum quisquam perspiciatis quia rerum consequatur totam quas\nsequi commodi repudiandae asperiores et saepe a",
  },
  {
    userId: 7,
    id: 70,
    title: "voluptatem laborum magni",
    body: "sunt repellendus quae\nest asperiores aut deleniti esse accusamus repellendus quia aut\nquia dolorem unde\neum tempora esse dolore",
  },
  {
    userId: 8,
    id: 71,
    title: "et iusto veniam et illum aut fuga",
    body: "occaecati a doloribus\niste saepe consectetur placeat eum voluptate dolorem et\nqui quo quia voluptas\nrerum ut id enim velit est perferendis",
  },
  {
    userId: 8,
    id: 72,
    title: "sint hic doloribus consequatur eos non id",
    body: "quam occaecati qui deleniti consectetur\nconsequatur aut facere quas exercitationem aliquam hic voluptas\nneque id sunt ut aut accusamus\nsunt consectetur expedita inventore velit",
  },
  {
    userId: 8,
    id: 73,
    title: "consequuntur deleniti eos quia temporibus ab aliquid at",
    body: "voluptatem cumque tenetur consequatur expedita ipsum nemo quia explicabo\naut eum minima consequatur\ntempore cumque quae est et\net in consequuntur voluptatem voluptates aut",
  },
  {
    userId: 8,
    id: 74,
    title: "enim unde ratione doloribus quas enim ut sit sapiente",
    body: "odit qui et et necessitatibus sint veniam\nmollitia amet doloremque molestiae commodi similique magnam et quam\nblanditiis est itaque\nquo et tenetur ratione occaecati molestiae tempora",
  },
  {
    userId: 8,
    id: 75,
    title: "dignissimos eum dolor ut enim et delectus in",
    body: "commodi non non omnis et voluptas sit\nautem aut nobis magnam et sapiente voluptatem\net laborum repellat qui delectus facilis temporibus\nrerum amet et nemo voluptate expedita adipisci error dolorem",
  },
  {
    userId: 8,
    id: 76,
    title: "doloremque officiis ad et non perferendis",
    body: "ut animi facere\ntotam iusto tempore\nmolestiae eum aut et dolorem aperiam\nquaerat recusandae totam odio",
  },
  {
    userId: 8,
    id: 77,
    title: "necessitatibus quasi exercitationem odio",
    body: "modi ut in nulla repudiandae dolorum nostrum eos\naut consequatur omnis\nut incidunt est omnis iste et quam\nvoluptates sapiente aliquam asperiores nobis amet corrupti repudiandae provident",
  },
  {
    userId: 8,
    id: 78,
    title: "quam voluptatibus rerum veritatis",
    body: "nobis facilis odit tempore cupiditate quia\nassumenda doloribus rerum qui ea\nillum et qui totam\naut veniam repellendus",
  },
  {
    userId: 8,
    id: 79,
    title: "pariatur consequatur quia magnam autem omnis non amet",
    body: "libero accusantium et et facere incidunt sit dolorem\nnon excepturi qui quia sed laudantium\nquisquam molestiae ducimus est\nofficiis esse molestiae iste et quos",
  },
  {
    userId: 8,
    id: 80,
    title: "labore in ex et explicabo corporis aut quas",
    body: "ex quod dolorem ea eum iure qui provident amet\nquia qui facere excepturi et repudiandae\nasperiores molestias provident\nminus incidunt vero fugit rerum sint sunt excepturi provident",
  },
  {
    userId: 9,
    id: 81,
    title: "tempora rem veritatis voluptas quo dolores vero",
    body: "facere qui nesciunt est voluptatum voluptatem nisi\nsequi eligendi necessitatibus ea at rerum itaque\nharum non ratione velit laboriosam quis consequuntur\nex officiis minima doloremque voluptas ut aut",
  },
  {
    userId: 9,
    id: 82,
    title: "laudantium voluptate suscipit sunt enim enim",
    body: "ut libero sit aut totam inventore sunt\nporro sint qui sunt molestiae\nconsequatur cupiditate qui iste ducimus adipisci\ndolor enim assumenda soluta laboriosam amet iste delectus hic",
  },
  {
    userId: 9,
    id: 83,
    title: "odit et voluptates doloribus alias odio et",
    body: "est molestiae facilis quis tempora numquam nihil qui\nvoluptate sapiente consequatur est qui\nnecessitatibus autem aut ipsa aperiam modi dolore numquam\nreprehenderit eius rem quibusdam",
  },
  {
    userId: 9,
    id: 84,
    title:
      "optio ipsam molestias necessitatibus occaecati facilis veritatis dolores aut",
    body: "sint molestiae magni a et quos\neaque et quasi\nut rerum debitis similique veniam\nrecusandae dignissimos dolor incidunt consequatur odio",
  },
  {
    userId: 9,
    id: 85,
    title: "dolore veritatis porro provident adipisci blanditiis et sunt",
    body: "similique sed nisi voluptas iusto omnis\nmollitia et quo\nassumenda suscipit officia magnam sint sed tempora\nenim provident pariatur praesentium atque animi amet ratione",
  },
  {
    userId: 9,
    id: 86,
    title: "placeat quia et porro iste",
    body: "quasi excepturi consequatur iste autem temporibus sed molestiae beatae\net quaerat et esse ut\nvoluptatem occaecati et vel explicabo autem\nasperiores pariatur deserunt optio",
  },
  {
    userId: 9,
    id: 87,
    title: "nostrum quis quasi placeat",
    body: "eos et molestiae\nnesciunt ut a\ndolores perspiciatis repellendus repellat aliquid\nmagnam sint rem ipsum est",
  },
  {
    userId: 9,
    id: 88,
    title: "sapiente omnis fugit eos",
    body: "consequatur omnis est praesentium\nducimus non iste\nneque hic deserunt\nvoluptatibus veniam cum et rerum sed",
  },
  {
    userId: 9,
    id: 89,
    title: "sint soluta et vel magnam aut ut sed qui",
    body: "repellat aut aperiam totam temporibus autem et\narchitecto magnam ut\nconsequatur qui cupiditate rerum quia soluta dignissimos nihil iure\ntempore quas est",
  },
  {
    userId: 9,
    id: 90,
    title: "ad iusto omnis odit dolor voluptatibus",
    body: "minus omnis soluta quia\nqui sed adipisci voluptates illum ipsam voluptatem\neligendi officia ut in\neos soluta similique molestias praesentium blanditiis",
  },
  {
    userId: 10,
    id: 91,
    title: "aut amet sed",
    body: "libero voluptate eveniet aperiam sed\nsunt placeat suscipit molestias\nsimilique fugit nam natus\nexpedita consequatur consequatur dolores quia eos et placeat",
  },
  {
    userId: 10,
    id: 92,
    title: "ratione ex tenetur perferendis",
    body: "aut et excepturi dicta laudantium sint rerum nihil\nlaudantium et at\na neque minima officia et similique libero et\ncommodi voluptate qui",
  },
  {
    userId: 10,
    id: 93,
    title: "beatae soluta recusandae",
    body: "dolorem quibusdam ducimus consequuntur dicta aut quo laboriosam\nvoluptatem quis enim recusandae ut sed sunt\nnostrum est odit totam\nsit error sed sunt eveniet provident qui nulla",
  },
  {
    userId: 10,
    id: 94,
    title: "qui qui voluptates illo iste minima",
    body: "aspernatur expedita soluta quo ab ut similique\nexpedita dolores amet\nsed temporibus distinctio magnam saepe deleniti\nomnis facilis nam ipsum natus sint similique omnis",
  },
  {
    userId: 10,
    id: 95,
    title: "id minus libero illum nam ad officiis",
    body: "earum voluptatem facere provident blanditiis velit laboriosam\npariatur accusamus odio saepe\ncumque dolor qui a dicta ab doloribus consequatur omnis\ncorporis cupiditate eaque assumenda ad nesciunt",
  },
  {
    userId: 10,
    id: 96,
    title: "quaerat velit veniam amet cupiditate aut numquam ut sequi",
    body: "in non odio excepturi sint eum\nlabore voluptates vitae quia qui et\ninventore itaque rerum\nveniam non exercitationem delectus aut",
  },
  {
    userId: 10,
    id: 97,
    title: "quas fugiat ut perspiciatis vero provident",
    body: "eum non blanditiis soluta porro quibusdam voluptas\nvel voluptatem qui placeat dolores qui velit aut\nvel inventore aut cumque culpa explicabo aliquid at\nperspiciatis est et voluptatem dignissimos dolor itaque sit nam",
  },
  {
    userId: 10,
    id: 98,
    title: "laboriosam dolor voluptates",
    body: "doloremque ex facilis sit sint culpa\nsoluta assumenda eligendi non ut eius\nsequi ducimus vel quasi\nveritatis est dolores",
  },
  {
    userId: 10,
    id: 99,
    title: "temporibus sit alias delectus eligendi possimus magni",
    body: "quo deleniti praesentium dicta non quod\naut est molestias\nmolestias et officia quis nihil\nitaque dolorem quia",
  },
  {
    userId: 10,
    id: 100,
    title: "at nam consequatur ea labore ea harum",
    body: "cupiditate quo est a modi nesciunt soluta\nipsa voluptas error itaque dicta in\nautem qui minus magnam et distinctio eum\naccusamus ratione error aut",
  },
];

export const newsData = [
  {
    title:
      "Major Crypto Exchanges Ready to Work in Russia Under Proposed Rules, Report",
    link: "https://news.bitcoin.com/major-crypto-exchanges-ready-to-work-in-russia-under-proposed-rules-report/",
    keywords: [
      "Exchanges",
      "ban",
      "Central Bank",
      "Crypto",
      "crypto exchanges",
      "crypto trading",
      "Cryptocurrencies",
      "Cryptocurrency",
      "entity",
      "Government",
      "Office",
      "Regulation",
      "Regulations",
      "Roadmap",
      "Rosfinmonitoring",
      "rules",
      "Russia",
      "russian",
      "Russian Federation",
      "trading",
    ],
    creator: ["Lubomir Tassev"],
    video_url: null,
    description:
      "Leading exchanges, polled by the Russian press, have indicated they are not afraid of the upcoming strict crypto regulations. A requirement for coin trading platforms to establish a local office is one of the proposals in a regulatory roadmap drafted by the government in Moscow. Cryptocurrency Exchanges to Set Up Shop in Russian Federation Some […]",
    content:
      "Leading exchanges, polled by the Russian press, have indicated they are not afraid of the upcoming strict crypto regulations. A requirement for coin trading platforms to establish a local office is one of the proposals in a regulatory roadmap drafted by the government in Moscow. Cryptocurrency Exchanges to Set Up Shop in Russian Federation Some of the world’s largest digital assets exchanges, interviewed by Kommersant, are not objecting to a potential requirement to establish permanent presence in Russia in order to continue to offer services to its citizens. The idea to oblige foreign-based platforms to do so is part of the government’s roadmap to regulate the country’s crypto space. The document, reportedly signed by Deputy Prime Minister Dmitry Chernyshenko, has been prepared as an alternative approach to Bank of Russia’s call for a ban on trading, among other crypto operations. With its hardline stance, the central bank has found itself in isolation as most other government institutions, including the Finance Ministry, favor regulation over prohibition. Among other requirements envisaged in the roadmap are those related to anti-money laundering efforts such as the sharing of transaction data with Rosfinmonitoring, Russia’s financial watchdog. Crypto market players will also have to put in place mechanisms to verify information about the ownership of the digital assets they are dealing with. Binance, the largest crypto exchange by volume, told the business daily it’s ready to open a branch or even register a legal entity in Russia, “if this contributes to the convenience of users and the security of operations.” Olga Goncharova, head of government relations for Russia and the CIS countries, said that Binance supports the regulatory roadmap as a step that “will make operations more understandable, transparent, and user-friendly” while also noting the proposals need further “calibration.” Another major crypto trading platform, Huobi, stated that it hopes for an “open dialogue with Russian regulators.” Its team believes that a constructive cryptocurrency law would help increase confidence in digital assets and exchanges in both individual and institutional investors. Crypto exchange AAX revealed it has no immediate plans to establish an office in the Russian Federation but it also said it may start working in this direction in case the regulations are approved. AAX is ready to comply with what it described as “legitimate” regulatory requirements. The exchange, which serves around half a million Russian residents, remarked that it keeps information about its clients, their balances, transactions, and trading activities. Russian lawmakers are now working on a new bill to fill the regulatory gaps remaining after the adoption of the law “On Digital Financial Assets.” The authors aim to define which entities will be allowed to work with cryptocurrencies, including crypto exchanges. Trading platforms incorporated abroad will be subject to a “special” registration regime, the Deputy Chair of the Security and Anti-Corruption Committee Andrey Lugovoy, one of the sponsors, told Russian media. Do you think crypto exchanges will be able to adapt to Russia’s upcoming rules for the sector? Share your thoughts on the subject in the comments section below.",
    pubDate: "2022-02-03 10:30:40",
    full_description:
      "Major Crypto Exchanges Ready to Work in Russia Under Proposed Rules, Report Leading exchanges, polled by the Russian press, have indicated they are not afraid of the upcoming strict crypto regulations. A requirement for coin trading platforms to establish a local office is one of the proposals in a regulatory roadmap drafted by the government in Moscow. Cryptocurrency Exchanges to Set Up Shop in Russian Federation Some of the world’s largest digital assets exchanges, interviewed by Kommersant, are not objecting to a potential requirement to establish permanent presence in Russia in order to continue to offer services to its citizens. The idea to oblige foreign-based platforms to do so is part of the government’s roadmap to regulate the country’s crypto space. The document, reportedly signed by Deputy Prime Minister Dmitry Chernyshenko, has been prepared as an alternative approach to Bank of Russia’s call for a ban on trading, among other crypto operations. With its hardline stance, the central bank has found itself in isolation as most other government institutions, including the Finance Ministry, favor regulation over prohibition. Among other requirements envisaged in the roadmap are those related to anti-money laundering efforts such as the sharing of transaction data with Rosfinmonitoring , Russia’s financial watchdog. Crypto market players will also have to put in place mechanisms to verify information about the ownership of the digital assets they are dealing with. Binance, the largest crypto exchange by volume, told the business daily it’s ready to open a branch or even register a legal entity in Russia, “if this contributes to the convenience of users and the security of operations.” Olga Goncharova, head of government relations for Russia and the CIS countries, said that Binance supports the regulatory roadmap as a step that “will make operations more understandable, transparent, and user-friendly” while also noting the proposals need further “calibration.” Another major crypto trading platform, Huobi, stated that it hopes for an “open dialogue with Russian regulators.” Its team believes that a constructive cryptocurrency law would help increase confidence in digital assets and exchanges in both individual and institutional investors. Crypto exchange AAX revealed it has no immediate plans to establish an office in the Russian Federation but it also said it may start working in this direction in case the regulations are approved. AAX is ready to comply with what it described as “legitimate” regulatory requirements. The exchange, which serves around half a million Russian residents, remarked that it keeps information about its clients, their balances, transactions, and trading activities. Russian lawmakers are now working on a new bill to fill the regulatory gaps remaining after the adoption of the law “On Digital Financial Assets.” The authors aim to define which entities will be allowed to work with cryptocurrencies, including crypto exchanges. Trading platforms incorporated abroad will be subject to a “special” registration regime, the Deputy Chair of the Security and Anti-Corruption Committee Andrey Lugovoy, one of the sponsors, told Russian media. Tags in this story ban , Central Bank , Crypto , crypto exchanges , crypto trading , Cryptocurrencies , Cryptocurrency , entity , Exchanges , Government , Office , Regulation , Regulations , Roadmap , Rosfinmonitoring , rules , Russia , russian , Russian Federation , trading Do you think crypto exchanges will be able to adapt to Russia’s upcoming rules for the sector? Share your thoughts on the subject in the comments section below. Lubomir Tassev Lubomir Tassev is a journalist from tech-savvy Eastern Europe who likes Hitchens’s quote: “Being a writer is what I am, rather than what I do.” Besides crypto, blockchain and fintech, international politics and economics are two other sources of inspiration. FTX Enters Japanese Crypto Market With Acquisition of Regulated Crypto Exchange EXCHANGES | 12 hours ago Crypto Exchange Binance Restricts 281 Nigerian Accounts — Some Requested by International Law Enforcement EXCHANGES | 3 days ago Image Credits : Shutterstock, Pixabay, Wiki Commons Previous article LABEL Foundation Looks to Revolutionise the Entertainment Industry in the Era of Web 3.0 Disclaimer : This article is for informational purposes only. It is not a direct offer or solicitation of an offer to buy or sell, or a recommendation or endorsement of any products, services, or companies. Bitcoin.com does not provide investment, tax, legal, or accounting advice. Neither the company nor the author is responsible, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any content, goods or services mentioned in this article. Read disclaimer Show comments More Popular News In Case You Missed It JPMorgan Lowers Its Bitcoin Fair Price Estimate to $38K Amidst Volatility Leading investment bank JPMorgan has changed its view on the estimate of bitcoin's price on a long-term basis. The institution had estimated a long-term price of $146K back in November when bitcoin was over $60K. One of the most important ... read more. Nansen Report Highlights Growth of Defi and NFTs in 2021 Nobel Laureate Paul Krugman Likens Crypto Market to Subprime Mortgage Crash — Warns Regulators Are Making the Same Mistake Russian Investors to Pass Exams Before Buying Cryptocurrencies, Draft Law Suggests Pop Star Justin Bieber Buys Bored Ape NFT for $1.29 Million, Pays More Than 300% Above Floor",
    image_url: null,
    source_id: "bitcoin",
    country: [
      "united states of america",
      "united kingdom",
      "india",
      "australia",
      "singapore",
      "saudi arabia",
      "canada",
    ],
    category: ["business"],
    language: "english",
  },
  -{
    title: "Bitcoin koersdaling valt hiermee samen, markt weer negatiever",
    link: "https://www.crypto-insiders.nl/nieuws/bitcoin/bitcoin-koersdaling-valt-hiermee-samen-markt-weer-negatiever/",
    keywords: [
      "Bitcoin nieuws",
      "Analyse",
      "Bearish",
      "Bitcoin",
      "Correlatie",
      "Koers",
      "Volume",
    ],
    creator: ["Kevin Schijven"],
    video_url: null,
    description:
      "Bitcoin (BTC) en de rest van de cryptocurrency-markt kregen gisteren weer een klap te verduren. Het marktsentiment begon de laatste tijd steeds meer bullish te worden, maar draait nu toch weer richting bearish om. Ondertussen ligt het handelsvolume nog steeds zeer laag, mede dankzij dat Azië het nieuwe jaar deze week viert. De angst neemt […]",
    content:
      "Bitcoin (BTC) en de rest van de cryptocurrency-markt kregen gisteren weer een klap te verduren. Het marktsentiment begon de laatste tijd steeds meer bullish te worden, maar draait nu toch weer richting bearish om. Ondertussen ligt het handelsvolume nog steeds zeer laag, mede dankzij dat Azië het nieuwe jaar deze week viert. De angst neemt volgens de Fear & Greed Index weer toe: Bitcoin Fear and Greed Index is 20 ~ Extreme FearCurrent price: $36,974 pic.twitter.com/93LZUuSaPk — Bitcoin Fear and Greed Index (@BitcoinFear) February 3, 2022 Bitcoin koers zakt 3,5% Gisterenochtend duwde bitcoin nog tegen weerstand rond $39.000 aan terwijl de koers boven $38.500 standhield. Gisterenmiddag verloor de bitcoin koers echter grip op deze $38.500 en kelderde naar $37.500. Daarmee leek de koers in eerste instantie wellicht een higher low te vestigen ten opzichte van de dip naar $37.000 op maandag. Bitcoin begon dan ook weer te stijgen, maar enkele uren later verloor de koers wederom grip en kelderde toen naar $37.000 op Binance en €32.775 op Bitvavo. Toch hield bitcoin hier gedurende nacht stand. UPDATE: Kort na publicatie verliest bitcoin toch grip op de $37.000 en de koers daalt momenteel richting $36.500. Daling gaat gepaard met twee zaken De dip van de bitcoin koers gaat gepaard met aandelen van grote technologie bedrijven die allemaal diep in de min staan. Meta (Facebook), Spotify, SnapChat, Netflix, Paypal en meer kregen gisteren allemaal een zware klap, soms wel meer dan 20%. Opvallend is dat de koersen van aandeelmarkten als S&P500 en en Nasdaq gisteren nog wel stegen waardoor de correlatie met bitcoin, die zeer hoog ligt, iets afneemt. De tweede dip van de bitcoin koers ging gisteren gepaard samen met een aanval op Wormhole, een zogenaamde cross-chain bridge tussen Ethereum (ETH) en Solana. Maar liefst $320 miljoen aan ETH werd gestolen door een hacker en vooral de SOL koers daalt daardoor hard. Hoe ver kan koers weer zakken? Volgens Whale Map is het volgende supportniveau al te vinden rond $36.650-$36.850. Daar kochten de whales namelijk veel BTC in: #Bitcoin pic.twitter.com/TDKPbwjEBS — whalemap (@whale_map) February 2, 2022 Mocht bitcoin hierdoorheen zakken, dan vinden we wellicht support rond $34.000-$35.000. Echter verwachten meerdere analisten dat we wellicht nog een hertest zullen zien van de recente low van $33.000, of wellicht zelfs van de $29.000-$30.000 als afgelopen zomer. #BTC I don't like long-term predictions, but I think we may visit the 30k/33k zone. Historically, the lower first standard deviation (1SD) of the VWAP has been support during the bull market. In addition, this zone is located between the annual POC and VALhttps://t.co/42FETJyG7i pic.twitter.com/qOoq6GCAX4 — M_Ernest_​₿ (@M_Ernest_) February 2, 2022 Toch zijn er ook genoeg bullish signalen te vinden voor de bitcoin koers. Zo zag de Canadese bitcoin exchange-traded fund (ETF), of beursgenoteerd fonds, van Purpose gisteren een van de grootste instromingen ooit: Purpose Bitcoin ETF had one of its biggest inflows yesterday. pic.twitter.com/1tDNv6Huo4 — Lex Moskovski (@mskvsk) February 2, 2022 Don't be the stooge selling to the Smart & Patient Money #HODLers %Supply last active 1+ years is increasing –> this means smart money is continuing to HODL, and not selling. The same playbook runs in many markets. FOLLOW THE SMART MONEY!#BuyBitcoin pic.twitter.com/KA1qKBAE9Q — Binkie Pondarosa (@BinkiePondarosa) February 2, 2022 Two #Bitcoin signals I have been waiting weeks to see flash bullish to signal a trend reversal are the Supertrend and MACD, both on the 3 day time frames They have been reliable in establishing a trend reversal I will update you when either of them flash bullish! Supertrend: pic.twitter.com/Wjnp9fw8vs — Matthew Hyland (@MatthewHyland_) February 2, 2022",
    pubDate: "2022-02-03 10:12:30",
    full_description: null,
    image_url: null,
    source_id: "crypto-insiders",
    country: ["netherland"],
    category: ["business"],
    language: "dutch",
  },
  -{
    title: "Crypto platform Wormhole hit by $A449 hack",
    link: "https://thewest.com.au/technology/security/crypto-platform-wormhole-hit-by-a449-hack-c-5558138",
    keywords: null,
    creator: ["Tom Wilson and Pushkala Aripaka"],
    video_url: null,
    description:
      "Finance platform Wormhole has been hacked, and cryptocurrency worth more than $A449 million stolen.",
    content: null,
    pubDate: "2022-02-03 10:05:15",
    full_description: null,
    image_url:
      "https://images.thewest.com.au/publication/C-5558138/5d5c53294e2f00f2b4c5621539c47275e56ccd32-16x9-x0y75w800h450.jpg",
    source_id: "thewest",
    country: ["australia"],
    category: ["technology"],
    language: "english",
  },
  -{
    title: "Crypto network Wormhole hit with possible $320m hack",
    link: "https://www.bangkokpost.com/business/2258251/crypto-network-wormhole-hit-with-possible-320m-hack",
    keywords: null,
    creator: null,
    video_url: null,
    description:
      "Hackers may have possibly stolen roughly $320 million (10.6 billion baht) worth of cryptocurrency from decentralised finance (DeFi) blockchain networks after a communication channel linking them was breached.",
    content: null,
    pubDate: "2022-02-03 08:55:00",
    full_description:
      'Hackers may have possibly stolen roughly $320 million (10.6 billion baht) worth of cryptocurrency from decentralised finance (DeFi) blockchain networks after a communication channel linking them was breached. Wormhole, which builds bridges between blockchains, facilitating transfers of any kind of information from one network to another, including Solana, tweeted on Wednesday that the network was "exploited" for 120,000 units of a cryptocurrency called wETH. So-called DeFi platforms allow users to lend, borrow and save - usually in cryptocurrencies - while bypassing traditional gatekeepers of finance such as banks. Wormhole has fixed the vulnerability in its system, it said in a follow-up tweet early on Thursday, but was still working to get the network back up. wETH is priced at nearly $2,649 apiece, according to trading platform Coinbase.',
    image_url: null,
    source_id: "bangkokpost",
    country: ["thailand"],
    category: ["business"],
    language: "english",
  },
  -{
    title: "Crypto network Wormhole hit with possible $320m hack",
    link: "https://www.bangkokpost.com/tech/2258251/crypto-network-wormhole-hit-with-possible-320m-hack",
    keywords: null,
    creator: null,
    video_url: null,
    description:
      "Hackers may have possibly stolen roughly $320 million (10.6 billion baht) worth of cryptocurrency from decentralised finance (DeFi) blockchain networks after a communication channel linking them was breached.",
    content: null,
    pubDate: "2022-02-03 08:55:00",
    full_description:
      'Hackers may have possibly stolen roughly $320 million (10.6 billion baht) worth of cryptocurrency from decentralised finance (DeFi) blockchain networks after a communication channel linking them was breached. Wormhole, which builds bridges between blockchains, facilitating transfers of any kind of information from one network to another, including Solana, tweeted on Wednesday that the network was "exploited" for 120,000 units of a cryptocurrency called wETH. So-called DeFi platforms allow users to lend, borrow and save - usually in cryptocurrencies - while bypassing traditional gatekeepers of finance such as banks. Wormhole has fixed the vulnerability in its system, it said in a follow-up tweet early on Thursday, but was still working to get the network back up. wETH is priced at nearly $2,649 apiece, according to trading platform Coinbase.',
    image_url: null,
    source_id: "bangkokpost",
    country: ["thailand"],
    category: ["technology"],
    language: "english",
  },
  -{
    title: "Russians own shocking amount of cryptocurrency, 12% of total value",
    link: "https://www.tweaktown.com/news/84382/russians-own-shocking-amount-of-cryptocurrency-12-total-value/index.html",
    keywords: null,
    creator: null,
    video_url: null,
    description:
      "A new report found that Russians hold a shocking amount of cryptocurrency equivalent to about 12% of total market value. Continue reading at TweakTown >",
    content: null,
    pubDate: "2022-02-03 08:31:02",
    full_description: null,
    image_url:
      "https://www.tweaktown.com/images/news/8/4/84382_01_russians-own-shocking-amount-of-cryptocurrency-12-total-value.jpg",
    source_id: "tweaktown",
    country: ["united states of america"],
    category: ["technology"],
    language: "english",
  },
  -{
    title:
      "India decides to allow cryptocurrencies – but imposes massive taxes on them",
    link: "https://metro.co.uk/2022/02/03/india-now-allows-cryptocurrencies-but-imposes-huge-taxes-on-profits-16039404/",
    keywords: ["Tech", "Bitcoin", "Cryptocurrency", "India", "NFT"],
    creator: ["Anugraha Sundaravelu"],
    video_url: null,
    description:
      "Earnings from cryptocurrencies and NFTs are now in India's highest tax band.",
    content:
      "The idea of paying more than 30% of their crypto profits in tax and other charges will not appeal to new investors. (Picture: SOPA Images/AP) India will not ban cryptocurrencies but will impose a heavy tax of 30% on income from them. The announcement was part of the country’s federal budget presentation this week, which placed earnings from cryptocurrencies and non-fungible tokens (NFTs) in India’s highest tax band. Additionally, losses from crypto sales could not be offset against other income, potentially discouraging trading and investment in digital assets. While this looks like bad news for crypto investors in the country, experts hope that the establishment of a formal tax framework means that the government had is warming up to the idea of digital currencies, reassuring corporates to enter the market. ‘We also hope this development removes any ambiguity for banks and they can provide financial services to the crypto industry,’ Nischal Shetty, CEO of WazirX, a virtual currency exchange, told Reuters. India’s federal budget placed earnings from cryptocurrencies and non-fungible tokens (NFTs) in India’s highest tax band. (Credits: Getty) The Indian government was known for draconian measures against crypto and even banning it at one point. So, the regulation is a welcome change for the Indian crypto community. However, the idea of paying more than 30% of their crypto profits in tax and other charges will not appeal to new investors. India’s central bank has previously voiced ‘serious concerns’ around private cryptocurrencies on the grounds that these could cause financial instability. As a result, several banks severed ties with crypto firms. In a U-turn from that stance, India’s Finance Minister Nirmala Sitaraman said that the central bank will introduce a digital currency in the next financial year using blockchain and other supporting technology. ‘The introduction of a central bank digital currency will give a big boost to the digital economy. Digital currency will also lead to a more efficient and cheaper currency management system,’ said Sitharaman. India’s Finance Secretary later confirmed that cryptocurrencies like Bitcoin or Ethereum will ‘never become legal tender’ i.e be used for payments. Users can instead use the digital rupee issued by the central bank to purchase non-digital assets. Industry estimates suggest there are 15 million to 20 million crypto investors in India, with total crypto holdings of around 400 billion rupees (£3.96 billion). No official data is available on the size of the Indian crypto market. MORE : Large-scale hack targets cryptocurrency YouTubers like Floyd Mayweather MORE : Influencers could face £250,000 fines in Spain for promoting cryptocurrency",
    pubDate: "2022-02-03 08:20:38",
    full_description:
      "India will not ban cryptocurrencies but will impose a heavy tax of 30% on income from them. The announcement was part of the country’s federal budget presentation this week, which placed earnings from cryptocurrencies and non-fungible tokens (NFTs) in India’s highest tax band. Additionally, losses from crypto sales could not be offset against other income, potentially discouraging trading and investment in digital assets. While this looks like bad news for crypto investors in the country, experts hope that the establishment of a formal tax framework means that the government had is warming up to the idea of digital currencies, reassuring corporates to enter the market. ‘We also hope this development removes any ambiguity for banks and they can provide financial services to the crypto industry,’ Nischal Shetty, CEO of WazirX, a virtual currency exchange, told Reuters. The Indian government was known for draconian measures against crypto and even banning it at one point. So, the regulation is a welcome change for the Indian crypto community. However, the idea of paying more than 30% of their crypto profits in tax and other charges will not appeal to new investors. India’s central bank has previously voiced ‘serious concerns’ around private cryptocurrencies on the grounds that these could cause financial instability. As a result, several banks severed ties with crypto firms. In a U-turn from that stance, India’s Finance Minister Nirmala Sitaraman said that the central bank will introduce a digital currency in the next financial year using blockchain and other supporting technology. ‘The introduction of a central bank digital currency will give a big boost to the digital economy. Digital currency will also lead to a more efficient and cheaper currency management system,’ said Sitharaman. India’s Finance Secretary later confirmed that cryptocurrencies like Bitcoin or Ethereum will ‘never become legal tender’ i.e be used for payments . Users can instead use the digital rupee issued by the central bank to purchase non-digital assets. Industry estimates suggest there are 15 million to 20 million crypto investors in India, with total crypto holdings of around 400 billion rupees (£3.96 billion). No official data is available on the size of the Indian crypto market. MORE : Large-scale hack targets cryptocurrency YouTubers like Floyd Mayweather MORE : Influencers could face £250,000 fines in Spain for promoting cryptocurrency Not convinced? Find out more »",
    image_url:
      "https://metro.co.uk/wp-content/uploads/2021/12/PRC_214913520.jpg?quality=90&strip=all",
    source_id: "metro",
    country: ["united kingdom"],
    category: ["top"],
    language: "english",
  },
  -{
    title:
      "Australian billionaire files lawsuit against Facebook over ‘scam ads’",
    link: "https://www.scmp.com/news/asia/australasia/article/3165684/australian-billionaire-files-lawsuit-against-facebook-over?utm_source=rss_feed",
    keywords: null,
    creator: ["Reuters"],
    video_url: null,
    description:
      "Iron ore magnate Andrew Forrest on Thursday said he was launching criminal proceedings against Meta Platform’s Facebook in an Australian court, alleging that it breached anti-money-laundering laws and its platform is used to scam Australians.Forrest, Australia’s richest man and chairman of Fortescue Metals Group, said he was taking the action to stop people losing money to clickbait advertising scams, such as ones using his image to promote cryptocurrency schemes.The lawsuit filed by Forrest in…",
    content: null,
    pubDate: "2022-02-03 07:28:45",
    image_url:
      "https://cdn.i-scmp.com/sites/default/files/styles/1280x720/public/d8/images/canvas/2022/02/03/90a9abe4-db33-4464-8c62-4813c965ef05_2ca2331c.jpg?itok=TEFlfLRV",
    source_id: "scmp",
    country: ["china"],
    category: ["top"],
    language: "english",
  },
  -{
    title: "Aantal NFT gebruikers neemt toe, maar zorgen omtrent witwassen ook",
    link: "https://www.crypto-insiders.nl/nieuws/altcoin/aantal-nft-gebruikers-neemt-toe-maar-zorgen-omtrent-witwassen-ook/",
    keywords: [
      "Altcoin nieuws",
      "Chainalysis",
      "NFT",
      "Polygon",
      "Wash trading",
      "Witwassen",
    ],
    creator: ["Timo Bult"],
    video_url: null,
    description:
      "De markt van non-fungible tokens (NFT’s) is nog altijd gloeiend heet. De grootste merken lanceren collecties en het aantal actieve gebruikers groeit flink. Toch kleeft er ook een schaduwzijde aan de NFT-markt. Polygon NFT-gebruikers op OpenSea stijgt Te beginnen met het goede nieuws. Het aantal actieve gebruikers op OpenSea van op Polygon (MATIC) gebaseerde NFT’s is namelijk […]",
    content:
      "De markt van non-fungible tokens (NFT’s) is nog altijd gloeiend heet. De grootste merken lanceren collecties en het aantal actieve gebruikers groeit flink. Toch kleeft er ook een schaduwzijde aan de NFT-markt. Polygon NFT-gebruikers op OpenSea stijgt Te beginnen met het goede nieuws. Het aantal actieve gebruikers op OpenSea van op Polygon (MATIC) gebaseerde NFT’s is namelijk gestegen. In december 2021 waren er nog zo’n 176.000 gebruikers, in januari 2022 steeg dit aantal naar 218.000. Ook het aantal Polygon NFT’s die verkocht zijn is gestegen. 1/ @0xPolygon's NFT activity on @opensea  in the past month has been phenomenal, with global brands consistently dropping their collections. Volume: $78.9 MnAvg. trades/ day: 102kEstimated monthly savings: $195.6 MnAvg. cost/ txn: $0.04 pic.twitter.com/MHoa7Zlwid — Simran Gogia (@Simran__02) February 2, 2022 In de laatste maand van 2021 gingen er nog 1,99 miljoen Polygon NFT’s over de toonbank bij OpenSea. Een maand later steeg dit aantal naar 2,68 miljoen. De gemiddelde waarde per gebruiker ging echter wel omlaag van $432 naar $360. Dit lijkt echter vooral te wijten aan de marktbrede crash waardoor veel cryptocurrencies minder waard werden. De data laat zien dat de NFT-gekte nog altijd aanhoudt en zelfs toe blijft nemen. Veel grote merken stappen de virtuele wereld in en lanceren collecties van digitale NFT’s. Door de unieke aard van een NFT zijn de tokens een interessant middel geworden voor de marketing van deze merken. Bovendien levert het natuurlijk ook een extra inkomstenbron op. Enkele bekende merken die NFT-collecties hebben gelanceerd zijn Nike, Lamborghini en Ubisoft. NFT wash trading en witwaspraktijken De ontwikkelingen zijn echter niet allemaal positief. On-chain analysebedrijf Chainalysis geeft namelijk in een nieuw rapport aan dat zij duidelijke signalen zien van wash trading en witwaspraktijken. Wash trading is het verkopen en tegelijk kopen van dezelfde NFT door dezelfde persoon. De persoon kan bijvoorbeeld zijn eigen NFT voor miljoenen euro’s verkopen aan zichzelf. Door de transactiegeschiedenis lijkt het nu alsof deze NFT een significante waarde heeft. “We hebben 262 gebruikers geïdentificeerd die meer dan 25 keer een NFT hebben verkocht aan een zelfgefinancierd adres,” stelt Chainalysis. 110 gebruikers zouden hiermee $8,9 miljoen hebben verdiend. Ook witwaspraktijken zijn reden tot zorgen vindt het bedrijf. In 2021 zouden deze praktijken weer zijn toegenomen. Dit kan de verdere ontwikkeling van de markt beschadigen: “Het witwassen van geld, en in het bijzonder overdrachten van gesanctioneerde cryptocurrency-bedrijven, vormt een groot risico voor het opbouwen van vertrouwen in NFT’s, en moet nauwer worden gecontroleerd door marktplaatsen, regelgevers en wetshandhavers,”",
    pubDate: "2022-02-03 06:04:43",
    full_description: null,
    image_url: null,
    source_id: "crypto-insiders",
    country: ["netherland"],
    category: ["business"],
    language: "dutch",
  },
  -{
    title:
      "Crypto theft is on the rise. Here's how the crimes are committed, and how you can protect yourself",
    link: "https://theconversation.com/crypto-theft-is-on-the-rise-heres-how-the-crimes-are-committed-and-how-you-can-protect-yourself-176027",
    keywords: null,
    creator: ["Aaron M. Lane", " Senior Lecturer in Law", " RMIT University"],
    video_url: null,
    description: null,
    content:
      "ShutterstockNews emerged overnight of the potential theft of more than US$326 million of Ethereum tokens from a blockchain bridge (which connects two blockchains so cryptocurrency can be exchanged between them). It’s no surprise. Crypto crime has been on the rise – especially since the pandemic began. How are these crimes committed? And what can you do to stay ahead of scammers? Direct theft vs scams There are two main ways criminals obtain cryptocurrency: stealing it directly, or using a scheme to trick people into handing it over. In 2021, crypto criminals directly stole a record US$3.2 billion (A$4.48 billion) worth of cryptocurrency, according to Chainalysis. That’s a fivefold increase from 2020. But schemes continue to overshadow outright theft, enabling scammers to lure US$7.8 billion worth of cryptocurrency from unsuspecting victims. Crypto crime is a fast-growing enterprise. The rise of the crypto economy and decentralised finance (or DeFi), coupled with record cryptocurrency prices in 2021, has provided criminals with lucrative opportunities. Australian data confirm the global trends. The Australian Consumer and Competition Commission reported more than A$26 million was lost to scams involving cryptocurrency in 2020 from 1,985 reports. In December, federal police told the ABC crypto scam losses for 2021 exceeded A$100 million. That’s despite many incidents likely left unreported, often due to embarrassment by victims. Theft from exchanges Most consumers obtain cryptocurrency from an exchange. This involves opening an account and depositing currency, such as Australian dollars, before converting it to a chosen cryptocurrency. Typically the cryptocurrency is held in a “custodial wallet”. That means it’s assigned to the consumer’s account, but the private keys that control the cryptocurrency are held by the exchange. In other words, the exchange stores the cryptocurrency on the consumer’s behalf. But just as a bank doesn’t hold all of its deposits in cash, an exchange will only hold enough cryptocurrency in “hot” wallets (connected to the internet) to facilitate customer transactions. For security, the remainder is held in “cold” wallets (not connected to the internet). Unlike a bank, however, the government does not have a financial claims scheme to guarantee cryptocurrency deposits if the exchange goes bust. The recent BitMart hack is a cautionary tale. On December 4, the exchange announced it had “identified a large-scale security breach” resulting in the theft of about US$150 million pls put AUD in brackets after any foreign dollar amount in crypto assets from hot wallets. BitMart temporarily suspended withdrawals and later promised it would use its “own funding to cover the incident and compensate affected users”. It’s unclear when this will happen, with the CNBC reporting in January that customers were still unable to access their cryptocurrency. BitMart wasn’t the first exchange to be hacked, and it won’t be the last. Similarly, consumers may be left with losses if an exchange fails for commercial reasons, rather than theft. Australians were left stranded in December when liquidators were appointed over Melbourne-based exchange myCryptoWallet. One way consumers can protect themselves from exchange theft, or insolvency, is to transfer their cryptocurrency from the exchange to a software wallet (a secure application installed on a computer or smartphone) or a hardware wallet (a hardware device that can be disconnected from the computer and internet). The cryptocurrency will then be under your direct control. But be warned, if you lose your private keys, you lose your cryptocurrency. Read more: The metaverse is money and crypto is king – why you'll be on a blockchain when you're virtual-world hopping Types of scams Drawing on the ACCC’s latest edition of the Little Black Book of Scams, the following types of scam are commonly observed in the cryptocurrency space, where the scammer is not personally known to the target: Email phishing The scammer sends unsolicited emails asking for personal login details, which can be used to steal cryptocurrency. Alternatively, they may offer “prizes” or “rewards” in exchange for a deposit. Investment scams The scammer creates a website that resembles a legitimate investment trading platform. It may be a fraudulent copy of a real business, or a completely bogus one. They may even post fake advertisements on social media platforms, with fake celebrity endorsements. In the latest news, billionaire mining magnate Andrew “Twiggy” Forrest has launched criminal proceedings against Meta (previously Facebook) for allowing scam ads using his image. More sophisticated operations will have multiple scammers emailing and calling victims to give the impression of being a legitimate organisation. After cryptocurrency deposits are made, victims may be able to “trade” on the fake platform but can’t withdraw their supposed earnings. Delay tactics include asking for further deposits to be made for fees or taxes. Romance scams The scammer creates a fake profile and matches with victims on a dating app or website. They may then ask for funds to help them with a personal crisis, such as needing a surgery. Or they may say they’re trading cryptocurrency and encourage the target to get involved, leading the victim into an investment scam, as described above. If a victim doesn’t already have a cryptocurrency exchange account, scammers may also coach them on how to open one. Some will mislead victims into installing remote access software on their computer, granting the scammer direct access to their internet banking or exchange account. Practical challenges There are practical legal challenges in the crypto crime environment. While reporting scams can be helpful in providing data and intelligence for regulators and law enforcement, it’s unlikely to result in the recovery of funds. Taking civil legal action may be possible, too, but identifying perpetrators is difficult. Since cryptocurrency is by its very nature global and decentralised, payments are often made to parties outside of Australia. So prevention is easier than a cure. The main way to avoid being scammed is to ensure you know exactly who you’re dealing with, transact through a reputable exchange and ensure all the channels you go through are verified. If an offer sounds too good to be true, it almost certainly is. Regulation on the horizon In Australia, cryptocurrency exchanges must be registered with AUSTRAC, in compliance with anti-money laundering and counter-terror financing obligations. But there are currently no other licensing requirements (such as capital requirements or cybersecurity, for example). Last year, the Senate Select Committee into Australia as a Technology and Financial Centre recommended a more comprehensive licensing framework. The Australian government agreed with the recommendation, and the federal treasury department is due to begin consulting on what this will look like. Mandatory measures to curb cryptocurrency crime at the exchange level will likely be high on the agenda. Aaron M. Lane works for the RMIT University Blockchain Innovation Hub and holds honorary research positions at the UCL Centre for Blockchain Technologies and the University of Divinity. Aaron is a member of the Digital Commerce Committee of the Law Council of Australia. Aaron is also Special Counsel at law firm Duxton Hill where he advises on matters involving cryptocurrency.",
    pubDate: "2022-02-03 05:59:33",
    full_description:
      "News emerged overnight of the potential theft of more than US$326 million of Ethereum tokens from a blockchain bridge (which connects two blockchains so cryptocurrency can be exchanged between them). It’s no surprise. Crypto crime has been on the rise – especially since the pandemic began. How are these crimes committed? And what can you do to stay ahead of scammers? There are two main ways criminals obtain cryptocurrency: stealing it directly, or using a scheme to trick people into handing it over. In 2021, crypto criminals directly stole a record US$3.2 billion (A$4.48 billion) worth of cryptocurrency, according to Chainalysis . That’s a fivefold increase from 2020. But schemes continue to overshadow outright theft, enabling scammers to lure US$7.8 billion worth of cryptocurrency from unsuspecting victims. Crypto crime is a fast-growing enterprise. The rise of the crypto economy and decentralised finance (or DeFi), coupled with record cryptocurrency prices in 2021, has provided criminals with lucrative opportunities. Australian data confirm the global trends. The Australian Consumer and Competition Commission reported more than A$26 million was lost to scams involving cryptocurrency in 2020 from 1,985 reports. In December, federal police told the ABC crypto scam losses for 2021 exceeded A$100 million. That’s despite many incidents likely left unreported, often due to embarrassment by victims. Most consumers obtain cryptocurrency from an exchange . This involves opening an account and depositing currency, such as Australian dollars, before converting it to a chosen cryptocurrency. Typically the cryptocurrency is held in a “custodial wallet”. That means it’s assigned to the consumer’s account, but the private keys that control the cryptocurrency are held by the exchange. In other words, the exchange stores the cryptocurrency on the consumer’s behalf. But just as a bank doesn’t hold all of its deposits in cash, an exchange will only hold enough cryptocurrency in “hot” wallets (connected to the internet) to facilitate customer transactions. For security, the remainder is held in “cold” wallets (not connected to the internet). Unlike a bank, however, the government does not have a financial claims scheme to guarantee cryptocurrency deposits if the exchange goes bust. The recent BitMart hack is a cautionary tale. On December 4, the exchange announced it had “identified a large-scale security breach” resulting in the theft of about US$150 million pls put AUD in brackets after any foreign dollar amount in crypto assets from hot wallets. BitMart temporarily suspended withdrawals and later promised it would use its “own funding to cover the incident and compensate affected users”. It’s unclear when this will happen, with the CNBC reporting in January that customers were still unable to access their cryptocurrency. BitMart wasn’t the first exchange to be hacked, and it won’t be the last. Similarly, consumers may be left with losses if an exchange fails for commercial reasons, rather than theft. Australians were left stranded in December when liquidators were appointed over Melbourne-based exchange myCryptoWallet . One way consumers can protect themselves from exchange theft, or insolvency, is to transfer their cryptocurrency from the exchange to a software wallet (a secure application installed on a computer or smartphone) or a hardware wallet (a hardware device that can be disconnected from the computer and internet). The cryptocurrency will then be under your direct control. But be warned, if you lose your private keys, you lose your cryptocurrency . Read more: The metaverse is money and crypto is king – why you'll be on a blockchain when you're virtual-world hopping Drawing on the ACCC’s latest edition of the Little Black Book of Scams , the following types of scam are commonly observed in the cryptocurrency space, where the scammer is not personally known to the target: Email phishing The scammer sends unsolicited emails asking for personal login details, which can be used to steal cryptocurrency. Alternatively, they may offer “prizes” or “rewards” in exchange for a deposit. Investment scams The scammer creates a website that resembles a legitimate investment trading platform. It may be a fraudulent copy of a real business, or a completely bogus one. They may even post fake advertisements on social media platforms, with fake celebrity endorsements. In the latest news , billionaire mining magnate Andrew “Twiggy” Forrest has launched criminal proceedings against Meta (previously Facebook) for allowing scam ads using his image. More sophisticated operations will have multiple scammers emailing and calling victims to give the impression of being a legitimate organisation. After cryptocurrency deposits are made, victims may be able to “trade” on the fake platform but can’t withdraw their supposed earnings. Delay tactics include asking for further deposits to be made for fees or taxes. Romance scams The scammer creates a fake profile and matches with victims on a dating app or website. They may then ask for funds to help them with a personal crisis, such as needing a surgery. Or they may say they’re trading cryptocurrency and encourage the target to get involved, leading the victim into an investment scam, as described above. If a victim doesn’t already have a cryptocurrency exchange account, scammers may also coach them on how to open one. Some will mislead victims into installing remote access software on their computer, granting the scammer direct access to their internet banking or exchange account. There are practical legal challenges in the crypto crime environment. While reporting scams can be helpful in providing data and intelligence for regulators and law enforcement, it’s unlikely to result in the recovery of funds. Taking civil legal action may be possible, too, but identifying perpetrators is difficult. Since cryptocurrency is by its very nature global and decentralised, payments are often made to parties outside of Australia. So prevention is easier than a cure. The main way to avoid being scammed is to ensure you know exactly who you’re dealing with, transact through a reputable exchange and ensure all the channels you go through are verified. If an offer sounds too good to be true, it almost certainly is. In Australia, cryptocurrency exchanges must be registered with AUSTRAC , in compliance with anti-money laundering and counter-terror financing obligations. But there are currently no other licensing requirements (such as capital requirements or cybersecurity, for example). Last year, the Senate Select Committee into Australia as a Technology and Financial Centre recommended a more comprehensive licensing framework. The Australian government agreed with the recommendation , and the federal treasury department is due to begin consulting on what this will look like. Mandatory measures to curb cryptocurrency crime at the exchange level will likely be high on the agenda.",
    image_url: null,
    source_id: "theconversation",
    country: ["australia"],
    category: ["technology", "science"],
    language: "english",
  },
];
