export const bookingData = [
  {
    id: 20,
    packageName: "Garbh Sanskar",
    hspName: "geeta devi",
    date: "14 Mar",
    status: "Completed",
    mode: "online",
    packageType: "individual",
    time: "8 am",
    healthAdvisor: "Nisha Das",
    customerName: "Shweta Keshari",
  },
  {
    id: 1,
    packageName: "Garbh Sanskar",
    hspName: "geeta devi",
    date: "14 Mar",
    status: "Completed",
    mode: "online",
    packageType: "individual",
    time: "8 am",
    healthAdvisor: "Nisha Das",
    customerName: "Ritika Sharma",
  },
  {
    id: 2,
    packageName: "Garbh Sanskar",
    hspName: "geeta devi",
    date: "15 Mar",
    status: "Cancelled",
    mode: "online",
    packageType: "individual",
    time: "8 am",
    healthAdvisor: "Nisha Das",
    customerName: "Ritika Sharma",
  },
  {
    id: 3,
    packageName: "Garbh Sanskar",
    hspName: "geeta devi",
    date: "15 Mar",
    status: "Pending",
    mode: "online",
    packageType: "individual",
    time: "0 am",
    healthAdvisor: "Nisha Das",
    customerName: "Ritika Sharma",
  },
  {
    id: 4,
    packageName: "Pregnancy Diet",
    hspName: "geeta devi",
    date: "15 Mar",
    status: "Hold",
    mode: "online",
    packageType: "individual",
    time: "0 am",
    healthAdvisor: "Nisha Das",
    customerName: "Shweta Keshari",
  },
  {
    id: 5,
    packageName: "Pregnancy Yoga",
    hspName: "geeta devi",
    date: "12 Mar",
    status: "Pending",
    mode: "online",
    packageType: "individual",
    time: "0 am",
    healthAdvisor: "Nisha Das",
    customerName: "Geeta",
  },
  {
    id: 6,
    packageName: "Pregnancy Yoga",
    hspName: "geeta devi",
    date: "12 Mar",
    status: "Completed",
    mode: "online",
    packageType: "individual",
    time: "0 am",
    healthAdvisor: "Nisha Das",
    customerName: "Shweta Keshari",
  },
  {
    id: 7,
    packageName: "Pregnancy Yoga",
    hspName: "geeta devi",
    date: "12 Mar",
    status: "Pending",
    mode: "online",
    packageType: "individual",
    time: "11 am",
    healthAdvisor: "Nisha Das",
    customerName: "Ritika Sharma",
  },
  {
    id: 8,
    packageName: "Pregnancy Yoga",
    hspName: "geeta devi",
    date: "12 Mar",
    status: "Completed",
    mode: "online",
    packageType: "individual",
    time: "0 am",
    healthAdvisor: "Nisha Das",
    customerName: "Shweta Keshari",
  },
  {
    id: 9,
    packageName: "Pregnancy Yoga",
    hspName: "Renuka Sharma",
    date: "10 Mar",
    status: "Cancelled",
    mode: "online",
    packageType: "individual",
    time: "0 am",
    healthAdvisor: "Nisha Das",
    customerName: "Shweta Keshari",
  },
  {
    id: 10,
    packageName: "Pregnancy Yoga",
    hspName: "geeta devi",
    date: "10 Mar",
    status: "Hold",
    mode: "online",
    packageType: "individual",
    time: "0 am",
    healthAdvisor: "Nisha Das",
    customerName: "Shweta Keshari",
  },
  {
    id: 11,
    packageName: "Pregnancy Diet",
    hspName: "geeta devi",
    date: "11 Mar",
    status: "Hold",
    mode: "online",
    packageType: "individual",
    time: "0 am",
    healthAdvisor: "Nisha Das",
    customerName: "Shweta Keshari",
  },
  {
    id: 12,
    packageName: "Pregnancy Yoga",
    hspName: "geeta devi",
    date: "11 Mar",
    status: "Cancelled",
    mode: "online",
    packageType: "individual",
    time: "0 am",
    healthAdvisor: "Nisha Das",
    customerName: "Shweta Keshari",
  },
  {
    id: 13,
    packageName: "Garbh Sanskar",
    hspName: "geeta devi",
    date: "11 Mar",
    status: "Hold",
    mode: "online",
    packageType: "individual",
    time: "0 am",
    healthAdvisor: "Nisha Das",
    customerName: "Geeta",
  },
  {
    id: 14,
    packageName: "Pregnancy Yoga",
    hspName: "geeta devi",
    date: "11 Mar",
    status: "Pending",
    mode: "online",
    packageType: "individual",
    time: "0 am",
    healthAdvisor: "Nisha Das",
    customerName: "Shweta Keshari",
  },
  {
    id: 15,
    packageName: "Garbh Sanskar",
    hspName: "geeta devi",
    date: "16 Mar",
    status: "Completed",
    mode: "online",
    packageType: "individual",
    time: "0 am",
    healthAdvisor: "Nisha Das",
    customerName: "Shweta Keshari",
  },
  {
    id: 16,
    packageName: "Pregnancy Yoga",
    hspName: "geeta devi",
    date: "15 Mar",
    status: "Hold",
    mode: "online",
    packageType: "individual",
    time: "0 am",
    healthAdvisor: "Nisha Das",
    customerName: "Shweta Keshari",
  },
];
